CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE account_type AS ENUM ('DEMO','LIVE');
CREATE TYPE permission_mode AS ENUM ('READ_ONLY','TRADING_ENABLED');

CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), telegram_user_id bigint UNIQUE NOT NULL, telegram_username varchar, first_name varchar, language varchar NOT NULL DEFAULT 'en', status varchar NOT NULL DEFAULT 'ACTIVE', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE mt5_accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), broker_name varchar NOT NULL, server varchar NOT NULL, login varchar NOT NULL, encrypted_password text NOT NULL, password_nonce text NOT NULL, key_version int NOT NULL DEFAULT 1, account_type account_type NOT NULL, permission_mode permission_mode NOT NULL DEFAULT 'READ_ONLY', is_verified boolean NOT NULL DEFAULT false, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,server,login));
CREATE TABLE ai_analyses (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), account_id uuid REFERENCES mt5_accounts(id), symbol varchar NOT NULL, timeframe varchar NOT NULL, market_data jsonb NOT NULL, analysis jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE trade_intents (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), account_id uuid NOT NULL REFERENCES mt5_accounts(id), analysis_id uuid REFERENCES ai_analyses(id), symbol varchar NOT NULL, side varchar NOT NULL CHECK(side IN('BUY','SELL')), volume numeric(18,8) NOT NULL CHECK(volume>0), entry_price numeric(18,8) NOT NULL, stop_loss numeric(18,8), take_profit numeric(18,8), status varchar NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), account_id uuid NOT NULL REFERENCES mt5_accounts(id), trade_intent_id uuid NOT NULL UNIQUE REFERENCES trade_intents(id), mt5_ticket bigint, symbol varchar NOT NULL, side varchar NOT NULL, volume numeric(18,8) NOT NULL, requested_price numeric(18,8) NOT NULL, executed_price numeric(18,8), stop_loss numeric(18,8), take_profit numeric(18,8), status varchar NOT NULL, broker_response jsonb, executed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE positions_snapshot (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), account_id uuid NOT NULL REFERENCES mt5_accounts(id), mt5_ticket bigint NOT NULL, symbol varchar NOT NULL, side varchar NOT NULL, volume numeric(18,8) NOT NULL, entry_price numeric(18,8) NOT NULL, current_price numeric(18,8), stop_loss numeric(18,8), take_profit numeric(18,8), profit_loss numeric(18,2), status varchar NOT NULL, captured_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,mt5_ticket));
CREATE TABLE risk_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), account_id uuid REFERENCES mt5_accounts(id), max_lot_size numeric(18,8) NOT NULL DEFAULT 0.10, max_open_positions int NOT NULL DEFAULT 5, max_trades_per_day int NOT NULL DEFAULT 20, max_daily_loss_amount numeric(18,2), max_daily_loss_percent numeric(8,4) DEFAULT 3, max_risk_per_trade_percent numeric(8,4) DEFAULT 1, max_slippage_points int NOT NULL DEFAULT 20, trading_enabled boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX risk_profile_scope ON risk_profiles(user_id,COALESCE(account_id,'00000000-0000-0000-0000-000000000000'));
CREATE TABLE user_settings (user_id uuid PRIMARY KEY REFERENCES users(id), live_trading_enabled boolean NOT NULL DEFAULT false, language varchar NOT NULL DEFAULT 'en', updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), account_id uuid REFERENCES mt5_accounts(id), event_type varchar NOT NULL, entity_type varchar NOT NULL, entity_id uuid, metadata jsonb NOT NULL DEFAULT '{}', ip inet, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE idempotency_keys (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), key_hash varchar NOT NULL, trade_intent_id uuid NOT NULL REFERENCES trade_intents(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,key_hash));
CREATE INDEX audit_user_created ON audit_logs(user_id,created_at DESC);
CREATE INDEX orders_user_created ON orders(user_id,created_at DESC);

